import {
  AlertCircle,
  Archive,
  ArrowLeft,
  BookText,
  BookUser,
  Check,
  ChevronLeft,
  ChevronRight,
  File,
  GraduationCap,
  HelpCircle,
  Home,
  Laptop,
  List,
  LogOut,
  Moon,
  MoveLeft,
  MoreHorizontal,
  PanelLeft,
  PlusCircle,
  SquarePen,
  Sun,
  User,
  X,
} from "lucide-react"

export const Icons = {
  ArrowLeft: ArrowLeft,
  Archive: Archive,
  BookText: BookText,
  BookUser: BookUser,
  Close: X,
  Check: Check,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  File: File,
  GraduationCap: GraduationCap,
  HelpCircle: HelpCircle,
  Home: Home,
  Logout: LogOut,
  List: List,
  Laptop: Laptop,
  MoveLeft: MoveLeft,
  Moon: Moon,
  MoreHorizontal: MoreHorizontal,
  PanelLeft: PanelLeft,
  PlusCircle: PlusCircle,
  SquarePen: SquarePen,
  Sun: Sun,
  User: User,
  Warning: AlertCircle,
}
